export const inventoryData = [
    {
      id: "1",
      name: "iPhone 15 Pro",
      sku: "ELE-IP15P",
      category: "Electronics",
      price: 999.99,
      stock: 45,
      lowStockThreshold: 10,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "2",
      name: "Samsung Galaxy S24",
      sku: "ELE-SGS24",
      category: "Electronics",
      price: 899.99,
      stock: 32,
      lowStockThreshold: 15,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "3",
      name: "Nike Air Max 270",
      sku: "CLO-NAM270",
      category: "Clothing",
      price: 150.0,
      stock: 8,
      lowStockThreshold: 10,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "4",
      name: "Adidas Ultraboost 22",
      sku: "CLO-AUB22",
      category: "Clothing",
      price: 180.0,
      stock: 0,
      lowStockThreshold: 5,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "5",
      name: 'MacBook Pro 16"',
      sku: "ELE-MBP16",
      category: "Electronics",
      price: 2499.99,
      stock: 12,
      lowStockThreshold: 5,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "6",
      name: "Instant Pot Duo 7-in-1",
      sku: "HOM-IPD7",
      category: "Home & Garden",
      price: 79.99,
      stock: 25,
      lowStockThreshold: 8,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "7",
      name: "The Great Gatsby",
      sku: "BOO-TGG",
      category: "Books",
      price: 12.99,
      stock: 150,
      lowStockThreshold: 20,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "8",
      name: "Yoga Mat Premium",
      sku: "SPO-YMP",
      category: "Sports",
      price: 45.99,
      stock: 3,
      lowStockThreshold: 10,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "9",
      name: "Coffee Maker Deluxe",
      sku: "HOM-CMD",
      category: "Home & Garden",
      price: 129.99,
      stock: 18,
      lowStockThreshold: 5,
      image: "/placeholder.svg?height=200&width=200",
    },
    {
      id: "10",
      name: "Wireless Headphones",
      sku: "ELE-WH",
      category: "Electronics",
      price: 199.99,
      stock: 67,
      lowStockThreshold: 15,
      image: "/placeholder.svg?height=200&width=200",
    },
  ];
  
  export const salesData = [
    {
      id: "1",
      customer: "John Doe",
      email: "john@example.com",
      product: "iPhone 15 Pro",
      amount: 999.99,
      date: "2024-01-15",
      status: "completed",
    },
    {
      id: "2",
      customer: "Jane Smith",
      email: "jane@example.com",
      product: 'MacBook Pro 16"',
      amount: 2499.99,
      date: "2024-01-14",
      status: "completed",
    },
    {
      id: "3",
      customer: "Bob Johnson",
      email: "bob@example.com",
      product: "Nike Air Max 270",
      amount: 150.0,
      date: "2024-01-13",
      status: "pending",
    },
  ];
  